### ISSUE TITLE
Update CHANGELOG for 4.0.2

### ISSUE THREAD

**Issue by PikachuEXE** [celluloid/timers#52]
<= Too busy to read all commits

**Comment by tarcieri** [comment]
I think per semantic versioning this should've been 4.1.0 actually

**Comment by digitalextremist** [comment]
Noted. Yank and recut, or rejoin semver at 4.1.* next release?

**Comment by PikachuEXE** [comment]
Should it be yanked due to invalid version?
I really have no idea :S

**Comment by digitalextremist** [comment]
Well, @tarcieri is right.. and this gem doesn't release that frequently -- as it shouldn't. So it should really keep to semver rather than anticipate a future release to catch up with.

I notice that last year `3.0.1` and `4.0.0` were released the same day, adhering to semver... so with that precedent I am going to yank and recut at `4.1.0` ... at the changelog update.

**Comment by digitalextremist** [comment]
Edit: Released a month apart, not same day. Just happened to be same day number in each month and I misread as same day. Either way.

**Comment by digitalextremist** [comment]
Recut at `4.1.0` with changelog.
